/* R2 GAMES V9 — real Railway tournaments + server news */
(function(){
 const toast=m=>{if(window.R2Wallet){ /* wallet toast remains available */ } alert(m)};
 window.R2ServerTournament={
  async create(){const name=document.getElementById('r2-tournament-name').value.trim();const size=+document.getElementById('r2-tournament-size').value;const game=document.getElementById('r2-tournament-game').value;const box=document.getElementById('r2-tournament-info');box.innerHTML='⏳ جاري إنشاء البطولة على السيرفر...';try{const r=await fetch('/api/tournaments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,size,game,hostName:'أنت'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر إنشاء البطولة');const t=d.tournament;box.innerHTML=`<div class="r2-card">🟢 تم إنشاء البطولة على <b>سيرفر R2</b><br><b>${t.name}</b> — ${t.game}<br>المسجلون: ${t.players}/${t.size}<br>أكواد الانضمام (${d.codes.length}):<br><small style="word-break:break-word">${d.codes.join(' | ')}</small></div>`}catch(e){box.innerHTML='🔴 '+e.message}},
  async join(){const code=document.getElementById('r2-tournament-code').value.trim().toUpperCase();const box=document.getElementById('r2-tournament-info');if(!code)return alert('اكتب كود الدعوة');box.innerHTML='⏳ جاري التحقق من الكود على السيرفر...';try{const r=await fetch('/api/tournaments/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر الانضمام');const t=d.tournament;box.innerHTML=`<div class="r2-card">✅ تم الانضمام بنجاح إلى <b>${t.name}</b><br>${t.players}/${t.size} لاعب — الحالة: ${t.status==='full'?'مكتملة 🏆':'مفتوحة 🟢'}</div>`}catch(e){box.innerHTML='🔴 '+e.message}},
 };
 if(window.R2){window.R2.createTournament=()=>R2ServerTournament.create();window.R2.joinTournament=()=>R2ServerTournament.join()}
 window.loadR2News=async function(){const el=document.getElementById('r2-news-list');if(!el)return;el.innerHTML='<div class="r2-card">⏳ جاري جلب الأخبار من السيرفر...</div>';try{const r=await fetch('/api/news?ts='+Date.now(),{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'تعذر جلب الأخبار');if(!d.ready){el.innerHTML='<div class="r2-card">⏳ السيرفر يقوم بتحديث الأخبار...<br><small>سيتم تحديثها تلقائيًا.</small></div>';setTimeout(window.loadR2News,2500);return}el.innerHTML=d.items.map(x=>`<div class="r2-card"><b>${String(x.title||'').replace(/</g,'&lt;')}</b><br><small>${x.source||''} ${x.publishedAt?'— '+x.publishedAt:''}</small><br><a href="${String(x.link||'#').replace(/"/g,'&quot;')}" target="_blank" rel="noopener">اقرأ الخبر ←</a></div>`).join('')||'<div class="r2-card">لا توجد أخبار الآن.</div>'}catch(e){el.innerHTML='<div class="r2-card">🔴 '+String(e.message||e)+'</div>';setTimeout(window.loadR2News,5000)}};
 const oldOpen=window.openModal;if(oldOpen&&!oldOpen.__v9){window.openModal=function(id){oldOpen(id);if(id==='newsModal')window.loadR2News()};window.openModal.__v9=true}
})();
